@TodoApi_HostAddress = http://localhost:5113

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{TodoApi_HostAddress}}/Todoes
Accept: application/json

{
  "Title" : "Leave and WFH Request",
  "Description" : "Ask for Leave and WFH Request",
  "Status" : 2,
  "Priority" : 2,
  "UserId" : "EF269CFF-6D57-4E9C-9FE7-D82B2CE90393"
}

###
GET {{TodoApi_HostAddress}}/api/Users

###

# Add User
POST {{TodoApi_HostAddress}}/api/Users
Accept: application/json

{
  "UserId" : "27171592-1a73-4c9c-93aa-23e0660cb511",
  "Name" : "Loki",
  "DOB" : "1980-01-19",
  "Gender": 0,
  "Profile" : NULL,
  "Credential" : {
    "Username": "loki_tva",
    "EmailId": "loki123@gmail.com",
    "Password": "loki123"
  }
}